# Generated by Django 6.0.5 on 2026-06-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'ELECTRONICS'), ('Groceries', 'GROCERIES'), ('Clothings', 'Спортивная одежда'), ('Accessories', 'Аксессуары'), ('Shoes', 'Обувь')], max_length=15, null=True),
        ),
    ]
