# Generated by Django 6.0.5 on 2026-07-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
